# Generated by Django 4.2.11 on 2024-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_protagonists'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movies_movi_name_98114c_idx'),
        ),
    ]
